services:
  app:
    image: rs:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV
      - BREVO_API_KEY
      - SECRET_KEY_BASE
      - GOOGLE_MAPS_API_KEY
      - DATABASE_URL
      - POSTHOG_API_KEY
      - POSTHOG_HOST
      - POSTHOG_TIMEOUT
      - TELEGRAM_BOT_TOKEN
      - FIGMA_API_KEY
      - SOLID_QUEUE_CONCURRENCY
      - SOLID_QUEUE_POLLING_INTERVAL
    ports:
      - "80:3000"
    volumes:
      - bundle_cache:/usr/local/bundle
    command: "/app/bin/rails server"

volumes:
  bundle_cache:
    driver: local
