services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rs:1.0
    env_file: .env
    environment:
      - DATABASE_URL=postgres://root:password@db:5433/root
    ports:
      - "80:3000"
    volumes:
      - bundle_cache:/usr/local/bundle
    command: bash -c "cd /app && bundle exec puma -C config/puma.rb -b tcp://0.0.0.0 -p 3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 2s
      retries: 5
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5433:5432"

volumes:
  postgres_data:
    driver: local
  bundle_cache:
    driver: local
